# Generated by Django 4.2.5 on 2023-09-20 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='cardname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='source',
        ),
    ]
